### ISSUE TITLE
Add custom fields to pos file

### ISSUE THREAD

**Issue by Knochi** [OneKiwiTech/kicad-component-placement#1]
We have a Fritsch SMT manual placement machine ([SM902Pro](https://www.fritsch-smt.de/en/manual-pick-place/sm902pro)). It requires a pos file with reference, position and a MPN. Would it possible to add one or two custom fields to the pos file?

**Comment by thanhduongvs** [comment]
add custom fileds look like:
![Screenshot from 2023-05-25 19-13-02](https://github.com/OneKiwiTech/kicad-component-placement/assets/8404232/4a94d114-b6d4-4468-9041-5042eeb0fef2)

**Comment by thanhduongvs** [comment]
@Knochi please update v1.1.2:
![Screenshot from 2023-05-28 20-57-26](https://github.com/OneKiwiTech/kicad-component-placement/assets/8404232/b3dba878-d205-4206-8121-cda5cc1c7614)
